/**************************************************************************
 * Copyright 2025 Corzia AB, Sweden.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **************************************************************************/
package org.corzia.oidc;

import java.util.Properties;

import jakarta.servlet.http.HttpServletRequest;

/**
 * Strategy interface for talking to a specific OpenID Connect provider.
 * <p>
 * Each implementation knows how to:
 * </p>
 * <ul>
 * <li>Build the provider-specific authorization URL for the redirect</li>
 * <li>Exchange an authorization code for tokens</li>
 * <li>Validate the ID token and normalize claims into {@link OidcUserInfo}</li>
 * </ul>
 *
 * <p>
 * The rest of the system (servlets, Shiro realm) should only depend on
 * this abstraction and {@link OidcUserInfo}, not on provider-specific
 * endpoints or claim names.
 * </p>
 */
public interface OidcClient {

    /**
     * Configures the client with the provided properties.
     * This is usually called after discovery via SPI.
     *
     * @param props configuration properties
     */
    void configure(Properties props);

    /**
     * Builds the full authorization URL for this provider.
     * <p>
     * Typical behavior:
     * </p>
     * <ul>
     * <li>Encode {@code client_id}, {@code response_type=code},
     * {@code redirect_uri}, {@code scope}, {@code state}, {@code nonce}</li>
     * <li>Return a URL that the browser should be redirected to</li>
     * </ul>
     *
     * @param request current HTTP request (for context path, etc.)
     * @param state   CSRF protection value generated by the app and stored in
     *                session
     * @param nonce   value used to bind ID token to this auth request
     * @return provider-specific authorization endpoint URL with query parameters
     */
    String buildAuthorizationUrl(HttpServletRequest req, String state, String nonce);

    /**
     * Exchanges an authorization {@code code} for tokens,
     * validates the ID token, and normalizes the resulting claims
     * into {@link OidcUserInfo}.
     * <p>
     * This method is typically called from the OIDC callback servlet.
     * It is responsible for:
     * </p>
     * <ul>
     * <li>Posting to the provider's token endpoint</li>
     * <li>Parsing the token response</li>
     * <li>Validating signature, issuer, audience, expiry and nonce</li>
     * <li>Extracting a usable principal, email and groups</li>
     * </ul>
     *
     * @param request       current HTTP request
     * @param code          authorization code received from the provider
     * @param expectedNonce nonce value stored in session for this flow
     * @return normalized user information
     * @throws Exception if token exchange or validation fails for any reason
     */
    OidcUserInfo exchangeCodeForUserInfo(HttpServletRequest req, String code, String expectedNonce)
            throws Exception;

    /**
     * @return the client ID registered with the provider.
     */
    String clientId();

    /**
     * @return the unique name of this provider (e.g., "google", "entra").
     */
    String getName();

    /**
     * @return the token endpoint URL for this provider.
     */
    String tokenEndpoint();

    /**
     * @return the client secret registered with the provider.
     */
    String clientSecret();

    /**
     * @return the URL of the icon/logo for this provider.
     */
    String imageUrl();

    /**
     * Checks if the client has been properly configured with at least a client
     * ID.
     *
     * @return true if configured, false otherwise
     */
    boolean isConfigured();
}
